### ISSUE TITLE
What  is this repository?

### ISSUE THREAD

**Issue by anuragdaksh7** [connordoner/crm#5]

**Comment by connordoner** [comment]
As explained in the [README which I've just committed](https://github.com/connordoner/crm/blob/main/README.md), this repository will host the source code for my new web application for managing information on and interactions with the people and organisations with whom I'm acquainted.

I'm going to share more about my intentions in this repository as I begin development, but the best comparison for now is something like [Monica CRM](https://www.monicahq.com) on my own personal tech stack and integrated with the platforms which I use.

Let me know if you have any other questions.
